<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="unittest.loader.ModuleImportFailure-20170928035610" tests="1" time="0.000">
	<testcase classname="unittest.loader.ModuleImportFailure" name="test" time="0.000">
		<error message="Failed to import test module: test
Traceback (most recent call last):
  File &quot;/usr/local/lib/python2.7/unittest/loader.py&quot;, line 254, in _find_tests
    module = self._get_module_from_name(name)
  File &quot;/usr/local/lib/python2.7/unittest/loader.py&quot;, line 232, in _get_module_from_name
    __import__(name)
  File &quot;/shared/test.py&quot;, line 1, in &lt;module&gt;
    from helpers.web_survey_helpers import *
  File &quot;/shared/helpers/web_survey_helpers.py&quot;, line 11, in &lt;module&gt;
    from selenium import webbrowser
ImportError: cannot import name webbrowser
" type="ImportError">
<![CDATA[ImportError: Failed to import test module: test
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/shared/test.py", line 1, in <module>
    from helpers.web_survey_helpers import *
  File "/shared/helpers/web_survey_helpers.py", line 11, in <module>
    from selenium import webbrowser
ImportError: cannot import name webbrowser

]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
